### PR TITLE
add in dependencies

### PR DESCRIPTION
**Pull request by hfukada**
you should do this.

### CODE REVIEW

**Comment by whalesalad** [comment]
We should remove Flask from the requirements. It's not being used anywhere here (and should not).

**Comment by whalesalad** [comment]
+1

**Comment by dbjohnson** [comment]
@whalesalad it is used in https://github.com/FarmLogs/python-utils/blob/master/flutil/flask_server.py

**Comment by whalesalad** [comment]
The string 'flask' is not mentioned anywhere in that file haha.

**Comment by dbjohnson** [comment]
oops - yep!  good call

**Comment by dbjohnson** [comment]
+1

**Pull request merged**
